import type { DiagnosisResult } from "./types";

// Sample diagnosis used by the static GitHub Pages demo (no backend there).
// The crawl-derived facts (entry URL, click depth, mechanical signals) are REAL values
// measured against kewpie.com. The per-item good/bad/level judgements are illustrative
// sample values — the live tool produces these via Claude. Clearly labelled as a demo.
export const sampleResult: DiagnosisResult = {
  inputUrl: "https://www.kewpie.com/",
  sustainabilityUrl: "https://www.kewpie.com/sustainability/",
  entryFound: true,
  clickDepth: 1,
  totalScore: 59.5,
  maxPoints: 70,
  scoreOutOf100: 85,
  model: "（サンプルデータ／ライブ診断は claude-sonnet-5）",
  screenshotDataUrl: null,
  crawlNotes: [
    "これは静的デモ用のサンプル結果です。ライブ診断（任意URL）はローカルで npm run dev を実行してください。",
  ],
  disclaimer:
    "Phase1（A/B/E=70点満点）の自動診断です。入口・クリック深度・機械判定シグナルは実測値ですが、項目別の良い点/悪い点はデモ用のサンプル値です。配点の一部は推定を含み、LLM採点には揺れがあります。",
  categories: [
    {
      id: "A",
      title: "サイトの使いやすさ・情報設計",
      score: 27.5,
      maxPoints: 30,
      items: [
        {
          id: "A1",
          categoryId: "A",
          title: "到達性",
          maxPoints: 5,
          score: 5,
          level: "good",
          good: ["トップから1クリックで到達（クリック深度=1）。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "A2",
          categoryId: "A",
          title: "グローバルナビ／ローカルメニュー",
          maxPoints: 5,
          score: 5,
          level: "good",
          good: ["ESG別・マテリアリティ別に整理され、下層まで一覧化。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "A3",
          categoryId: "A",
          title: "サイト内検索",
          maxPoints: 3,
          score: 3,
          level: "good",
          good: ["サイト内検索を検出。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "A4",
          categoryId: "A",
          title: "パンくず・現在地表示",
          maxPoints: 3,
          score: 3,
          level: "good",
          good: ["パンくず（現在地表示）を検出。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "A5",
          categoryId: "A",
          title: "統合報告書・データ集への導線",
          maxPoints: 5,
          score: 5,
          level: "good",
          good: ["統合報告書とESGデータ集の双方へ導線あり。"],
          bad: [],
          evidenceUrls: [
            "https://www.kewpie.com/ir/library/kewpie-report/",
            "https://www.kewpie.com/sustainability/esg/",
          ],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "A6",
          categoryId: "A",
          title: "アクセシビリティ",
          maxPoints: 5,
          score: 2.5,
          level: "partial",
          good: ["文字サイズ・コントラストは概ね良好。"],
          bad: ["アクセシビリティ方針の明記が確認できず。詳細はAA基準の人的監査が必要。"],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: true,
        },
        {
          id: "A7",
          categoryId: "A",
          title: "モバイル・表示速度",
          maxPoints: 4,
          score: 4,
          level: "good",
          good: ["レスポンシブ対応で表示も軽快。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
      ],
    },
    {
      id: "B",
      title: "ESG共通・戦略性",
      score: 21,
      maxPoints: 25,
      items: [
        {
          id: "B1",
          categoryId: "B",
          title: "トップメッセージ",
          maxPoints: 4,
          score: 4,
          level: "good",
          good: ["社長メッセージがサステナビリティを自分の言葉で語っている。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/message/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "B2",
          categoryId: "B",
          title: "理念・ビジョン／価値創造ストーリー",
          maxPoints: 4,
          score: 4,
          level: "good",
          good: ["「食を通じた社会貢献」という理念とサステナビリティが接続。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "B3",
          categoryId: "B",
          title: "マテリアリティ",
          maxPoints: 6,
          score: 6,
          level: "good",
          good: ["重要課題ごとに目標・実績・SDGsが紐づく。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "B4",
          categoryId: "B",
          title: "目標・実績・進捗",
          maxPoints: 5,
          score: 2.5,
          level: "partial",
          good: ["主要KPIに目標値を提示。"],
          bad: ["経年実績・達成率の一覧性が弱い。数値の正確性は人的確認が必要。"],
          evidenceUrls: ["https://www.kewpie.com/sustainability/esg/"],
          notDetected: false,
          needsHumanReview: true,
        },
        {
          id: "B5",
          categoryId: "B",
          title: "外部評価・イニシアチブ",
          maxPoints: 3,
          score: 3,
          level: "good",
          good: ["外部評価・加盟イニシアチブを掲載。"],
          bad: [],
          evidenceUrls: [
            "https://www.kewpie.com/sustainability/human-rights/healthcare-management/",
          ],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "B6",
          categoryId: "B",
          title: "英語開示の同等性",
          maxPoints: 3,
          score: 1.5,
          level: "partial",
          good: ["英語サイトが存在。"],
          bad: ["日本語に比べ英語のサステナビリティ開示が薄い。"],
          evidenceUrls: ["https://www.kewpie.com/"],
          notDetected: false,
          needsHumanReview: false,
        },
      ],
    },
    {
      id: "E",
      title: "ガバナンス G",
      score: 11,
      maxPoints: 15,
      items: [
        {
          id: "E1",
          categoryId: "E",
          title: "コーポレート・ガバナンス体制",
          maxPoints: 5,
          score: 2.5,
          level: "partial",
          good: ["取締役会構成を開示。"],
          bad: ["スキルマトリックスが確認できず。"],
          evidenceUrls: ["https://www.kewpie.com/sustainability/governance/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "E2",
          categoryId: "E",
          title: "リスク管理・コンプライアンス",
          maxPoints: 4,
          score: 4,
          level: "good",
          good: ["リスクマネジメント体制とコンプライアンス方針を明示。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/sustainability/governance/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "E3",
          categoryId: "E",
          title: "各種ポリシー",
          maxPoints: 3,
          score: 1.5,
          level: "partial",
          good: ["主要ポリシーの一部を掲載。"],
          bad: ["税務方針など一部ポリシーが確認できず。"],
          evidenceUrls: ["https://www.kewpie.com/sustainability/governance/"],
          notDetected: false,
          needsHumanReview: false,
        },
        {
          id: "E4",
          categoryId: "E",
          title: "株主・投資家との対話開示",
          maxPoints: 3,
          score: 3,
          level: "good",
          good: ["対話テーマと経営への反映事項を具体掲載。"],
          bad: [],
          evidenceUrls: ["https://www.kewpie.com/ir/"],
          notDetected: false,
          needsHumanReview: false,
        },
      ],
    },
  ],
};
